name: Pull Request

on: [pull_request]

jobs:
  image-tag:
    name: Extract Image Tag
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@v3
      - id: tag
        run: |
          TAG="${GITHUB_HEAD_REF}-$(git rev-parse --short HEAD)"
          echo "::notice title=Docker Image Tag::${TAG}"
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
  build-api-image:
    name: Build and Push API Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    needs:
      - image-tag
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ github.repository }}/django:${{ needs.image-tag.outputs.tag }}
  build-mock-api-server:
    name: Build and Push Mock API Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    needs:
      - image-tag
      - build-api-image
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: mock/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/mock-api:${{ needs.image-tag.outputs.tag }}
#  create-migrated-database:
#    name: Create Migrated Database
#    runs-on: ubuntu-22.04
#    needs:
#      - image-tag
#      - build-api-image
#    container:
#      image: ghcr.io/${{ github.repository }}/django:${{ needs.image-tag.outputs.tag }}
#      credentials:
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#      volumes:
#        - ${{ github.workspace }}/db:/usr/app/db
#    steps:
#      - name: Migrate database
#        run: |
#          python /usr/app/manage.py migrate
#      - name: Upload SQLite database
#        uses: actions/upload-artifact@v3
#        with:
#          name: db.sqlite3
#          path: ${{ github.workspace }}/db/db.sqlite3
  run-contract-tests:
    name: Run API Contract Tests
    runs-on: ubuntu-22.04
    needs:
      - image-tag
      - build-api-image
#      - create-migrated-database
    services:
      django:
        image: ghcr.io/${{ github.repository }}/django:${{ needs.image-tag.outputs.tag }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        volumes:
          - ${{ github.workspace }}/api/docs:/usr/app/api/docs
        options: --entrypoint /usr/app/bin/migrate-and-run
#        volumes:
#          - ${{ github.workspace }}/db:/usr/app/db
    container:
      image: apiaryio/dredd:14.0.0
    steps:
#      - name: Download SQLite database
#        uses: actions/download-artifact@v3
#        with:
#          name: db.sqlite3
#          path: db/db.sqlite3
#      - name: Run API
#        uses: addnab/docker-run-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          image: ghcr.io/${{ github.repository }}/django:${{ needs.image-tag.outputs.tag }}
#          options: -p 8000:8000
#          run: |
#            mkdir db
#            python manage.py migrate
#            python manage.py runserver
      - name: Run tests
        run: dredd ${{ github.workspace }}/api/docs http://django:8000
